# Generated by Django 5.0.6 on 2024-07-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='orders',
            new_name='order',
        ),
    ]
